# POST
POST http://localhost:3000/api/word-groups/
Content-Type: application/json

{
      "translations": [
        {"languageName": "English", "word": "House", "synonyms": ["Home", "Building"]},
        {"languageName": "Spanish", "word": "Casa", "synonyms": ["Hogar", "Edificio"]},
        {"languageName": "French", "word": "Maison", "synonyms": ["Domicile", "Bâtiment"]},
        {"languageName": "German", "word": "Haus", "synonyms": ["Heim", "Gebäude"]},
        {"languageName": "Finnish", "word": "Talo", "synonyms": ["Koti", "Rakennus"]},
        {"languageName": "Swedish", "word": "Hus", "synonyms": ["Hem", "Byggnad"]}
      ],
      "tags": ["home", "architecture"]
    }


###
GET http://localhost:3000/api/word-groups